// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKTQQh2DtG_SNyor7IE2gpMw1uuZGYJoQ',
    appId: '1:408820575975:web:db431a49ba499344573c42',
    messagingSenderId: '408820575975',
    projectId: 'smart-90a5b',
    authDomain: 'smart-90a5b.firebaseapp.com',
    databaseURL: 'https://smart-90a5b-default-rtdb.firebaseio.com',
    storageBucket: 'smart-90a5b.appspot.com',
    measurementId: 'G-KQS5JCKXHG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0GssdXuT9XupN925o1hijyiBt2-6TbCw',
    appId: '1:408820575975:android:c9678e2f88fa2c79573c42',
    messagingSenderId: '408820575975',
    projectId: 'smart-90a5b',
    storageBucket: 'smart-90a5b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEwIqcWzqJe0ewOwdxNInBvWodwzqja6Y',
    appId: '1:408820575975:ios:9d1ecb4efe5472e8573c42',
    messagingSenderId: '408820575975',
    projectId: 'smart-90a5b',
    storageBucket: 'smart-90a5b.appspot.com',
    iosClientId: '408820575975-jru3lor1v6m4t4hveudlk94m8a30i0v1.apps.googleusercontent.com',
    iosBundleId: 'com.example.animation',
  );
}
